# Pipeline for building package documentation

name: Build Documentation $(Build.SourceBranch) by $(Build.RequestedFor)

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: '3.11'
      # architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements-dev.txt
    displayName: 'Install dependencies'

  - script: |
      sphinx-apidoc -f -e -M -T -o docs/source src/my_package *utils *cli
      cd docs
      make html
    displayName: 'Build Sphinx docs'

  - script: |
      pip install build
      python -m build --sdist
      mkdir ./docs/build/html/dist
      mv ./dist/*.tar.gz ./docs/build/html/dist/
    displayName: 'Build and copy package'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish HTML'
    inputs:
      pathToPublish: './docs/build/html'
      artifactName: 'docs_html'
